---
title: "git_00"
author: "Ellyn Molzer"
date: "Sept.2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

And cannot pleasures, while they last,  
Be actual unless, when past,  
They leave us shuddering and aghast,  
With anguish smarting?  
And cannot friends be firm and fast,  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Love at the lips was touch   
As sweet as I could bear;  
And once that seemed too   
much;  
I lived on air   


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Once upon a midnight dreary, while I pondered, weak and weary,  
Over many a quaint and curious volume of forgotten lore —  
While I nodded, nearly napping, suddenly there came a tapping,  
As of some one gently rapping, rapping at my chamber door.  
“’Tis some visiter,” I muttered, “tapping at my chamber door —  
Only this and nothing more.”  
  
Ah, distinctly I remember it was in the bleak December;  
And each separate dying ember wrought its ghost upon the floor.  
Eagerly I wished the morrow; — vainly I had sought to borrow. 
From my books surcease of sorrow — sorrow for the lost Lenore —  
For the rare and radiant maiden whom the angels name Lenore —  
Nameless here for evermore.  
  
And the silken, sad, uncertain rustling of each purple curtain. 
Thrilled me — filled me with fantastic terrors never felt before;  
So that now, to still the beating of my heart, I stood repeating. 
“ ’Tis some visiter entreating entrance at my chamber door —  
Some late visiter entreating entrance at my chamber door; —  
This it is and nothing more.”  
